# Generated by Django 4.0 on 2023-07-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketReviews',
        ),
    ]
