# Generated by Django 4.0 on 2023-06-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'UserFollow', 'verbose_name_plural': 'UserFollows'},
        ),
    ]
